---
- name: Install Zabbix Server on Ubuntu 22.04
  hosts: ksm_monitoring
  become: yes
  tasks:
    - name: Update APT Cache
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - wget
          - gnupg
        state: present

    - name: Download Zabbix Repository Package
      shell: wget -O /tmp/zabbix-release.deb https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-1+ubuntu22.04_all.deb

    - name: Install Zabbix Repository Package
      shell: dpkg -i /tmp/zabbix-release.deb

    - name: Update APT Cache Again
      apt:
        update_cache: yes

    - name: Install Zabbix Server, Frontend, and Agent
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-nginx-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present

    - name: Install Python PIP
      apt:
        name: python3-pip
        state: present

    - name: Install PyMySQL Python Module
      pip:
        name: pymysql
        state: present

    - name: Create Zabbix Database
      community.mysql.mysql_db:
        name: zabbix
        state: present
        encoding: utf8mb4
        collation: utf8mb4_bin
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create Zabbix User
      community.mysql.mysql_user:
        name: zabbix
        host: localhost
        password: "zabbix"
        priv: "zabbix.*:ALL"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Set Global MySQL Variable log_bin_trust_function_creators to 1
      community.mysql.mysql_query:
        query: "SET GLOBAL log_bin_trust_function_creators = 1;"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Import Initial Zabbix Database Schema
      shell: zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -uzabbix -pzabbix zabbix
      args:
        executable: /bin/bash

    - name: Set Global MySQL Variable log_bin_trust_function_creators to 0
      community.mysql.mysql_query:
        query: "SET GLOBAL log_bin_trust_function_creators = 0;"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Configure the database for Zabbix server
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^#?DBPassword='
        line: 'DBPassword=zabbix'
        state: present

    - name: Enable and Start Zabbix Server
      service:
        name: zabbix-server
        enabled: yes
        state: started

    - name: Enable and Start Zabbix Agent
      service:
        name: zabbix-agent
        enabled: yes
        state: started

    - name: Enable and Start Nginx
      service:
        name: nginx
        enabled: yes
        state: started
