---
- name: Install Nginx, Php8.1 on Ubuntu 22.04
  hosts: ksm_monitoring
  become: yes
  tasks:
    - name: Update APT Cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Enable and Start Nginx Service
      service:
        name: nginx
        enabled: yes
        state: started

    - name: Install PHP 8.1-FPM and Extensions
      apt:
        name:
          - php8.1-fpm
          - php8.1-bcmath
          - php8.1-bz2
          - php8.1-cgi
          - php8.1-cli
          - php8.1-common
          - php8.1-curl
          - php8.1-gd
          - php8.1-gmagick
          - php8.1-gmp
          - php8.1-intl
          - php8.1-ldap
          - php8.1-mbstring
          - php8.1-memcache
          - php8.1-memcached
          - php8.1-mongodb
          - php8.1-mysql
          - php8.1-redis
          - php8.1-soap
          - php8.1-tidy
          - php8.1-uuid
          - php8.1-xml
          - php8.1-yaml
          - php8.1-zip
        state: present

    - name: Enable and Start PHP 8.1-FPM Service
      service:
        name: php8.1-fpm
        enabled: yes
        state: started
